CREATE TABLE runs(scope TEXT NOT NULL,id TEXT NOT NULL,target_id TEXT NOT NULL,root_run_id TEXT NOT NULL,parent_run_id TEXT NOT NULL,call_node_id TEXT NOT NULL,depth INTEGER NOT NULL CHECK(depth>=0),session_id TEXT NOT NULL,idempotency_key TEXT NOT NULL,workflow_resource_id TEXT NOT NULL,workflow_commit_id TEXT NOT NULL,definition_digest TEXT NOT NULL,action_id TEXT NOT NULL,inputs_json BLOB NOT NULL,trigger_json BLOB NOT NULL,status TEXT NOT NULL CHECK(status IN ('queued','running','stopping','succeeded','failed','stopped','canceled','interrupted')),termination TEXT NOT NULL,error_json BLOB NOT NULL,result_json BLOB NOT NULL,nodes_json BLOB NOT NULL,cleanup_errors_json BLOB NOT NULL,created_at INTEGER NOT NULL,started_at INTEGER NOT NULL,finished_at INTEGER NOT NULL,revision INTEGER NOT NULL CHECK(revision>0),bytes INTEGER NOT NULL CHECK(bytes>=0),PRIMARY KEY(scope,id),CHECK((status IN ('queued','running','stopping'))=(finished_at=0)));
CREATE UNIQUE INDEX runs_idempotency ON runs(scope,idempotency_key) WHERE idempotency_key<>'';
CREATE INDEX runs_created ON runs(scope,created_at,id);
CREATE INDEX runs_target ON runs(scope,target_id,created_at,id);
CREATE INDEX runs_root ON runs(scope,root_run_id,created_at,id);
CREATE INDEX runs_session ON runs(scope,session_id,created_at,id) WHERE session_id<>'';
CREATE INDEX runs_workflow ON runs(scope,workflow_resource_id,created_at,id);
CREATE INDEX runs_open ON runs(scope,created_at,id) WHERE status IN ('queued','running','stopping');
CREATE INDEX runs_finished ON runs(scope,finished_at,id) WHERE finished_at>0;
CREATE TABLE sessions(scope TEXT NOT NULL,id TEXT NOT NULL,target_id TEXT NOT NULL,experiment_resource_id TEXT NOT NULL,experiment_commit_id TEXT NOT NULL,root_run_id TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('open','stopping','closed','interrupted')),stop_intent_json BLOB NOT NULL,opened_at INTEGER NOT NULL,closed_at INTEGER NOT NULL,revision INTEGER NOT NULL CHECK(revision>0),bytes INTEGER NOT NULL CHECK(bytes>=0),PRIMARY KEY(scope,id),CHECK((status IN ('open','stopping'))=(closed_at=0)));
CREATE UNIQUE INDEX sessions_live_target ON sessions(scope,target_id) WHERE status IN ('open','stopping');
CREATE INDEX sessions_opened ON sessions(scope,opened_at,id);
CREATE INDEX sessions_target ON sessions(scope,target_id,opened_at,id);
CREATE INDEX sessions_experiment ON sessions(scope,experiment_resource_id,opened_at,id);
CREATE TABLE recordings(scope TEXT NOT NULL,id TEXT NOT NULL,session_id TEXT NOT NULL,run_id TEXT NOT NULL,kind TEXT NOT NULL,path TEXT NOT NULL,metadata_json BLOB NOT NULL,created_at INTEGER NOT NULL,bytes INTEGER NOT NULL CHECK(bytes>=0),PRIMARY KEY(scope,id));
CREATE INDEX recordings_created ON recordings(scope,created_at,id);
CREATE INDEX recordings_session ON recordings(scope,session_id,created_at,id) WHERE session_id<>'';
CREATE INDEX recordings_run ON recordings(scope,run_id,created_at,id);
