// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: protocol/storage.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Scope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Workspace     string                 `protobuf:"bytes,3,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scope) Reset() {
	*x = Scope{}
	mi := &file_protocol_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scope) ProtoMessage() {}

func (x *Scope) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scope.ProtoReflect.Descriptor instead.
func (*Scope) Descriptor() ([]byte, []int) {
	return file_protocol_storage_proto_rawDescGZIP(), []int{0}
}

func (x *Scope) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Scope) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Scope) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseId    string                 `protobuf:"bytes,1,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	Schema        string                 `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	Revision      string                 `protobuf:"bytes,3,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_protocol_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_protocol_storage_proto_rawDescGZIP(), []int{1}
}

func (x *Token) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *Token) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *Token) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

type Query struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Collection     string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Keys           []string               `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	Index          string                 `protobuf:"bytes,3,opt,name=index,proto3" json:"index,omitempty"`
	EqualJson      [][]byte               `protobuf:"bytes,4,rep,name=equal_json,json=equalJson,proto3" json:"equal_json,omitempty"`
	After          string                 `protobuf:"bytes,5,opt,name=after,proto3" json:"after,omitempty"`
	Limit          int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	IncludeDeleted bool                   `protobuf:"varint,7,opt,name=include_deleted,json=includeDeleted,proto3" json:"include_deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_protocol_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_protocol_storage_proto_rawDescGZIP(), []int{2}
}

func (x *Query) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *Query) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *Query) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *Query) GetEqualJson() [][]byte {
	if x != nil {
		return x.EqualJson
	}
	return nil
}

func (x *Query) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *Query) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Query) GetIncludeDeleted() bool {
	if x != nil {
		return x.IncludeDeleted
	}
	return false
}

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         *Scope                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Queries       []*Query               `protobuf:"bytes,2,rep,name=queries,proto3" json:"queries,omitempty"`
	At            *Token                 `protobuf:"bytes,3,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_protocol_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_protocol_storage_proto_rawDescGZIP(), []int{3}
}

func (x *SnapshotRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *SnapshotRequest) GetQueries() []*Query {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *SnapshotRequest) GetAt() *Token {
	if x != nil {
		return x.At
	}
	return nil
}

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Deleted       bool                   `protobuf:"varint,3,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Missing       bool                   `protobuf:"varint,4,opt,name=missing,proto3" json:"missing,omitempty"`
	DataJson      []byte                 `protobuf:"bytes,5,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	Collection    string                 `protobuf:"bytes,6,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_protocol_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_protocol_storage_proto_rawDescGZIP(), []int{4}
}

func (x *Record) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Record) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Record) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *Record) GetMissing() bool {
	if x != nil {
		return x.Missing
	}
	return false
}

func (x *Record) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

func (x *Record) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

type QueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Records       []*Record              `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	NextAfter     string                 `protobuf:"bytes,3,opt,name=next_after,json=nextAfter,proto3" json:"next_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_protocol_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_protocol_storage_proto_rawDescGZIP(), []int{5}
}

func (x *QueryResult) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *QueryResult) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *QueryResult) GetNextAfter() string {
	if x != nil {
		return x.NextAfter
	}
	return ""
}

type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         *Scope                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Token         *Token                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Results       []*QueryResult         `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_protocol_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_protocol_storage_proto_rawDescGZIP(), []int{6}
}

func (x *SnapshotResponse) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *SnapshotResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *SnapshotResponse) GetResults() []*QueryResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type Mutation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Collection      string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Key             string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	ExpectedVersion string                 `protobuf:"bytes,3,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	Delete          bool                   `protobuf:"varint,4,opt,name=delete,proto3" json:"delete,omitempty"`
	DataJson        []byte                 `protobuf:"bytes,5,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Mutation) Reset() {
	*x = Mutation{}
	mi := &file_protocol_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutation) ProtoMessage() {}

func (x *Mutation) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutation.ProtoReflect.Descriptor instead.
func (*Mutation) Descriptor() ([]byte, []int) {
	return file_protocol_storage_proto_rawDescGZIP(), []int{7}
}

func (x *Mutation) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *Mutation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Mutation) GetExpectedVersion() string {
	if x != nil {
		return x.ExpectedVersion
	}
	return ""
}

func (x *Mutation) GetDelete() bool {
	if x != nil {
		return x.Delete
	}
	return false
}

func (x *Mutation) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

type BatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         *Scope                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Expected      *Token                 `protobuf:"bytes,2,opt,name=expected,proto3" json:"expected,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Mutations     []*Mutation            `protobuf:"bytes,4,rep,name=mutations,proto3" json:"mutations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_protocol_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_protocol_storage_proto_rawDescGZIP(), []int{8}
}

func (x *BatchRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *BatchRequest) GetExpected() *Token {
	if x != nil {
		return x.Expected
	}
	return nil
}

func (x *BatchRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BatchRequest) GetMutations() []*Mutation {
	if x != nil {
		return x.Mutations
	}
	return nil
}

type ReceiptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         *Scope                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiptRequest) Reset() {
	*x = ReceiptRequest{}
	mi := &file_protocol_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptRequest) ProtoMessage() {}

func (x *ReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptRequest.ProtoReflect.Descriptor instead.
func (*ReceiptRequest) Descriptor() ([]byte, []int) {
	return file_protocol_storage_proto_rawDescGZIP(), []int{9}
}

func (x *ReceiptRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *ReceiptRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ReceiptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	Token         *Token                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	CommittedAt   string                 `protobuf:"bytes,4,opt,name=committed_at,json=committedAt,proto3" json:"committed_at,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Durability    string                 `protobuf:"bytes,6,opt,name=durability,proto3" json:"durability,omitempty"`
	Versions      []*Record              `protobuf:"bytes,7,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiptResponse) Reset() {
	*x = ReceiptResponse{}
	mi := &file_protocol_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptResponse) ProtoMessage() {}

func (x *ReceiptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptResponse.ProtoReflect.Descriptor instead.
func (*ReceiptResponse) Descriptor() ([]byte, []int) {
	return file_protocol_storage_proto_rawDescGZIP(), []int{10}
}

func (x *ReceiptResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ReceiptResponse) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ReceiptResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *ReceiptResponse) GetCommittedAt() string {
	if x != nil {
		return x.CommittedAt
	}
	return ""
}

func (x *ReceiptResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *ReceiptResponse) GetDurability() string {
	if x != nil {
		return x.Durability
	}
	return ""
}

func (x *ReceiptResponse) GetVersions() []*Record {
	if x != nil {
		return x.Versions
	}
	return nil
}

type NamedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         *Scope                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	DatabaseId    string                 `protobuf:"bytes,2,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	Schema        string                 `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	Module        string                 `protobuf:"bytes,4,opt,name=module,proto3" json:"module,omitempty"`
	Operation     string                 `protobuf:"bytes,5,opt,name=operation,proto3" json:"operation,omitempty"`
	RequestId     string                 `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,7,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamedRequest) Reset() {
	*x = NamedRequest{}
	mi := &file_protocol_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedRequest) ProtoMessage() {}

func (x *NamedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedRequest.ProtoReflect.Descriptor instead.
func (*NamedRequest) Descriptor() ([]byte, []int) {
	return file_protocol_storage_proto_rawDescGZIP(), []int{11}
}

func (x *NamedRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *NamedRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *NamedRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *NamedRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *NamedRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *NamedRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *NamedRequest) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

type NamedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipt       *ReceiptResponse       `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"`
	ResultJson    []byte                 `protobuf:"bytes,2,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamedResponse) Reset() {
	*x = NamedResponse{}
	mi := &file_protocol_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedResponse) ProtoMessage() {}

func (x *NamedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedResponse.ProtoReflect.Descriptor instead.
func (*NamedResponse) Descriptor() ([]byte, []int) {
	return file_protocol_storage_proto_rawDescGZIP(), []int{12}
}

func (x *NamedResponse) GetReceipt() *ReceiptResponse {
	if x != nil {
		return x.Receipt
	}
	return nil
}

func (x *NamedResponse) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

var File_protocol_storage_proto protoreflect.FileDescriptor

const file_protocol_storage_proto_rawDesc = "" +
	"\n" +
	"\x16protocol/storage.proto\x12\x0fxgc2.storage.v1\"W\n" +
	"\x05Scope\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x1c\n" +
	"\tworkspace\x18\x03 \x01(\tR\tworkspace\"\\\n" +
	"\x05Token\x12\x1f\n" +
	"\vdatabase_id\x18\x01 \x01(\tR\n" +
	"databaseId\x12\x16\n" +
	"\x06schema\x18\x02 \x01(\tR\x06schema\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\tR\brevision\"\xc5\x01\n" +
	"\x05Query\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\tR\x04keys\x12\x14\n" +
	"\x05index\x18\x03 \x01(\tR\x05index\x12\x1d\n" +
	"\n" +
	"equal_json\x18\x04 \x03(\fR\tequalJson\x12\x14\n" +
	"\x05after\x18\x05 \x01(\tR\x05after\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\x12'\n" +
	"\x0finclude_deleted\x18\a \x01(\bR\x0eincludeDeleted\"\x99\x01\n" +
	"\x0fSnapshotRequest\x12,\n" +
	"\x05scope\x18\x01 \x01(\v2\x16.xgc2.storage.v1.ScopeR\x05scope\x120\n" +
	"\aqueries\x18\x02 \x03(\v2\x16.xgc2.storage.v1.QueryR\aqueries\x12&\n" +
	"\x02at\x18\x03 \x01(\v2\x16.xgc2.storage.v1.TokenR\x02at\"\xa5\x01\n" +
	"\x06Record\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x18\n" +
	"\adeleted\x18\x03 \x01(\bR\adeleted\x12\x18\n" +
	"\amissing\x18\x04 \x01(\bR\amissing\x12\x1b\n" +
	"\tdata_json\x18\x05 \x01(\fR\bdataJson\x12\x1e\n" +
	"\n" +
	"collection\x18\x06 \x01(\tR\n" +
	"collection\"\x7f\n" +
	"\vQueryResult\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x121\n" +
	"\arecords\x18\x02 \x03(\v2\x17.xgc2.storage.v1.RecordR\arecords\x12\x1d\n" +
	"\n" +
	"next_after\x18\x03 \x01(\tR\tnextAfter\"\xa6\x01\n" +
	"\x10SnapshotResponse\x12,\n" +
	"\x05scope\x18\x01 \x01(\v2\x16.xgc2.storage.v1.ScopeR\x05scope\x12,\n" +
	"\x05token\x18\x02 \x01(\v2\x16.xgc2.storage.v1.TokenR\x05token\x126\n" +
	"\aresults\x18\x03 \x03(\v2\x1c.xgc2.storage.v1.QueryResultR\aresults\"\x9c\x01\n" +
	"\bMutation\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12)\n" +
	"\x10expected_version\x18\x03 \x01(\tR\x0fexpectedVersion\x12\x16\n" +
	"\x06delete\x18\x04 \x01(\bR\x06delete\x12\x1b\n" +
	"\tdata_json\x18\x05 \x01(\fR\bdataJson\"\xc8\x01\n" +
	"\fBatchRequest\x12,\n" +
	"\x05scope\x18\x01 \x01(\v2\x16.xgc2.storage.v1.ScopeR\x05scope\x122\n" +
	"\bexpected\x18\x02 \x01(\v2\x16.xgc2.storage.v1.TokenR\bexpected\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x127\n" +
	"\tmutations\x18\x04 \x03(\v2\x19.xgc2.storage.v1.MutationR\tmutations\"]\n" +
	"\x0eReceiptRequest\x12,\n" +
	"\x05scope\x18\x01 \x01(\v2\x16.xgc2.storage.v1.ScopeR\x05scope\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"\x8d\x02\n" +
	"\x0fReceiptResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12,\n" +
	"\x05token\x18\x03 \x01(\v2\x16.xgc2.storage.v1.TokenR\x05token\x12!\n" +
	"\fcommitted_at\x18\x04 \x01(\tR\vcommittedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\tR\texpiresAt\x12\x1e\n" +
	"\n" +
	"durability\x18\x06 \x01(\tR\n" +
	"durability\x123\n" +
	"\bversions\x18\a \x03(\v2\x17.xgc2.storage.v1.RecordR\bversions\"\xed\x01\n" +
	"\fNamedRequest\x12,\n" +
	"\x05scope\x18\x01 \x01(\v2\x16.xgc2.storage.v1.ScopeR\x05scope\x12\x1f\n" +
	"\vdatabase_id\x18\x02 \x01(\tR\n" +
	"databaseId\x12\x16\n" +
	"\x06schema\x18\x03 \x01(\tR\x06schema\x12\x16\n" +
	"\x06module\x18\x04 \x01(\tR\x06module\x12\x1c\n" +
	"\toperation\x18\x05 \x01(\tR\toperation\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\x12!\n" +
	"\fpayload_json\x18\a \x01(\fR\vpayloadJson\"l\n" +
	"\rNamedResponse\x12:\n" +
	"\areceipt\x18\x01 \x01(\v2 .xgc2.storage.v1.ReceiptResponseR\areceipt\x12\x1f\n" +
	"\vresult_json\x18\x02 \x01(\fR\n" +
	"resultJson2\x8a\x03\n" +
	"\aStorage\x12O\n" +
	"\bSnapshot\x12 .xgc2.storage.v1.SnapshotRequest\x1a!.xgc2.storage.v1.SnapshotResponse\x12H\n" +
	"\x05Batch\x12\x1d.xgc2.storage.v1.BatchRequest\x1a .xgc2.storage.v1.ReceiptResponse\x12L\n" +
	"\aReceipt\x12\x1f.xgc2.storage.v1.ReceiptRequest\x1a .xgc2.storage.v1.ReceiptResponse\x12F\n" +
	"\x05Named\x12\x1d.xgc2.storage.v1.NamedRequest\x1a\x1e.xgc2.storage.v1.NamedResponse\x12N\n" +
	"\vNamedResult\x12\x1f.xgc2.storage.v1.ReceiptRequest\x1a\x1e.xgc2.storage.v1.NamedResponseB4Z2github.com/XGC-Team/xgc2-storage/protocol;protocolb\x06proto3"

var (
	file_protocol_storage_proto_rawDescOnce sync.Once
	file_protocol_storage_proto_rawDescData []byte
)

func file_protocol_storage_proto_rawDescGZIP() []byte {
	file_protocol_storage_proto_rawDescOnce.Do(func() {
		file_protocol_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_storage_proto_rawDesc), len(file_protocol_storage_proto_rawDesc)))
	})
	return file_protocol_storage_proto_rawDescData
}

var file_protocol_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_protocol_storage_proto_goTypes = []any{
	(*Scope)(nil),            // 0: xgc2.storage.v1.Scope
	(*Token)(nil),            // 1: xgc2.storage.v1.Token
	(*Query)(nil),            // 2: xgc2.storage.v1.Query
	(*SnapshotRequest)(nil),  // 3: xgc2.storage.v1.SnapshotRequest
	(*Record)(nil),           // 4: xgc2.storage.v1.Record
	(*QueryResult)(nil),      // 5: xgc2.storage.v1.QueryResult
	(*SnapshotResponse)(nil), // 6: xgc2.storage.v1.SnapshotResponse
	(*Mutation)(nil),         // 7: xgc2.storage.v1.Mutation
	(*BatchRequest)(nil),     // 8: xgc2.storage.v1.BatchRequest
	(*ReceiptRequest)(nil),   // 9: xgc2.storage.v1.ReceiptRequest
	(*ReceiptResponse)(nil),  // 10: xgc2.storage.v1.ReceiptResponse
	(*NamedRequest)(nil),     // 11: xgc2.storage.v1.NamedRequest
	(*NamedResponse)(nil),    // 12: xgc2.storage.v1.NamedResponse
}
var file_protocol_storage_proto_depIdxs = []int32{
	0,  // 0: xgc2.storage.v1.SnapshotRequest.scope:type_name -> xgc2.storage.v1.Scope
	2,  // 1: xgc2.storage.v1.SnapshotRequest.queries:type_name -> xgc2.storage.v1.Query
	1,  // 2: xgc2.storage.v1.SnapshotRequest.at:type_name -> xgc2.storage.v1.Token
	4,  // 3: xgc2.storage.v1.QueryResult.records:type_name -> xgc2.storage.v1.Record
	0,  // 4: xgc2.storage.v1.SnapshotResponse.scope:type_name -> xgc2.storage.v1.Scope
	1,  // 5: xgc2.storage.v1.SnapshotResponse.token:type_name -> xgc2.storage.v1.Token
	5,  // 6: xgc2.storage.v1.SnapshotResponse.results:type_name -> xgc2.storage.v1.QueryResult
	0,  // 7: xgc2.storage.v1.BatchRequest.scope:type_name -> xgc2.storage.v1.Scope
	1,  // 8: xgc2.storage.v1.BatchRequest.expected:type_name -> xgc2.storage.v1.Token
	7,  // 9: xgc2.storage.v1.BatchRequest.mutations:type_name -> xgc2.storage.v1.Mutation
	0,  // 10: xgc2.storage.v1.ReceiptRequest.scope:type_name -> xgc2.storage.v1.Scope
	1,  // 11: xgc2.storage.v1.ReceiptResponse.token:type_name -> xgc2.storage.v1.Token
	4,  // 12: xgc2.storage.v1.ReceiptResponse.versions:type_name -> xgc2.storage.v1.Record
	0,  // 13: xgc2.storage.v1.NamedRequest.scope:type_name -> xgc2.storage.v1.Scope
	10, // 14: xgc2.storage.v1.NamedResponse.receipt:type_name -> xgc2.storage.v1.ReceiptResponse
	3,  // 15: xgc2.storage.v1.Storage.Snapshot:input_type -> xgc2.storage.v1.SnapshotRequest
	8,  // 16: xgc2.storage.v1.Storage.Batch:input_type -> xgc2.storage.v1.BatchRequest
	9,  // 17: xgc2.storage.v1.Storage.Receipt:input_type -> xgc2.storage.v1.ReceiptRequest
	11, // 18: xgc2.storage.v1.Storage.Named:input_type -> xgc2.storage.v1.NamedRequest
	9,  // 19: xgc2.storage.v1.Storage.NamedResult:input_type -> xgc2.storage.v1.ReceiptRequest
	6,  // 20: xgc2.storage.v1.Storage.Snapshot:output_type -> xgc2.storage.v1.SnapshotResponse
	10, // 21: xgc2.storage.v1.Storage.Batch:output_type -> xgc2.storage.v1.ReceiptResponse
	10, // 22: xgc2.storage.v1.Storage.Receipt:output_type -> xgc2.storage.v1.ReceiptResponse
	12, // 23: xgc2.storage.v1.Storage.Named:output_type -> xgc2.storage.v1.NamedResponse
	12, // 24: xgc2.storage.v1.Storage.NamedResult:output_type -> xgc2.storage.v1.NamedResponse
	20, // [20:25] is the sub-list for method output_type
	15, // [15:20] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_protocol_storage_proto_init() }
func file_protocol_storage_proto_init() {
	if File_protocol_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_storage_proto_rawDesc), len(file_protocol_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_storage_proto_goTypes,
		DependencyIndexes: file_protocol_storage_proto_depIdxs,
		MessageInfos:      file_protocol_storage_proto_msgTypes,
	}.Build()
	File_protocol_storage_proto = out.File
	file_protocol_storage_proto_goTypes = nil
	file_protocol_storage_proto_depIdxs = nil
}
